####################
# Service settings:
####################

service-port: 443
discovery-address: 172.31.18.122:8000
external-service-address: viktorkob.ml
external-protocol: https://
spring.main.allow-bean-definition-overriding: true

####################
# Deduced settings:
####################

eureka.instance.hostname: ${external-service-address}
spring.boot.admin.url: ${external-protocol}service-user:password@${external-service-address}:${service-port}
eureka.client.service-url.defaultZone: http://service-user:password@${discovery-address}${infrastructure-context-path}/eureka/
eureka.instance.prefer-ip-address: true

####################
# Hystrix settings:
####################

hystrix.command.default.execution.isolation.strategy: THREAD
hystrix.command.default.execution.thread.timeoutInMilliseconds: 300000
hystrix.command.default.execution.timeout.enabled: false